apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: asia-south1-docker.pkg.dev/gcp-demo-508702/voting-app/worker:8400f9210f8b50ea1e930e485d35c58f40fe55bf
        name: worker
