apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: asia-south1-docker.pkg.dev/gcp-demo-508702/voting-app/worker:f7f4dc67eab84e1a44c56d799f49efc2b58827b7
        name: worker
